version: '3.5'

services:
  app:
    build:
      context: ./docker
    volumes:
      - .:/application/
#      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    command:
      - ./docker/endless_process
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"

networks:
  default: