version: '3.5'

services:
  app:
    build:
      context: ./docker
    volumes:
      - .:/application/
#      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    command:
      - ./docker/entrypoint
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8181:8181"
      - "9256:9256"
#      - "9100:9100"
    healthcheck:
      test: curl --fail http://localhost:8181/healthcheck || exit 1
      interval: 15s
      timeout: 1s
      retries: 3
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
  grafana:
    #13882 - id process exporter dashboard
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-treemap-panel
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      TZ: "Europe/Moscow"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  grafana_storage: {}

networks:
  default: