parameters:
  app.name: TestCaseConsoleApp
  app.version: 0.0.1
  app.start_execution_time: !php/const START_EXECUTION_TIME
  app.path: !php/const APP_PATH
  app.php_binary_path: !php/const PHP_BINARY

services:
  _defaults:
    autowire: true

  event_dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: Symfony\Component\EventDispatcher\EventDispatcher

imports:
  - { resource: ../src/Modules/CommandsQueue/config/services.yaml }
  - { resource: ../src/Modules/Email/config/services.yaml }
  - { resource: ../src/Modules/Notify/config/services.yaml }
  - { resource: ../src/Modules/Shared/config/services.yaml }
  - { resource: ../src/Core/config/services.yaml }