parameters:
  app.name: TestCaseConsoleApp
  app.version: 0.0.1
  app.start_execution_time: !php/const START_EXECUTION_TIME
  app.path: !php/const APP_PATH

services:
  _defaults:
    autowire: true
    bind:
      '$appPath': '%app.path%'

  App\:
    resource: '../src/*'
    exclude:
      - '../src/functions.php'
      - '../src/metrics.php'
      - '../src/Enum'
      - '../src/Metrics'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: [ 'app.command' ]

  app.event_dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'

  App\Core\EventDispatcher\Configurator\EventDispatcherConfigurator:
    arguments:
      $startExecutionTime: '%app.start_execution_time%'

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    configurator: '@App\Core\EventDispatcher\Configurator\EventDispatcherConfigurator'

  App\Core\App:
    class: App\Core\App
    public: true
    arguments:
      $commands: !tagged_iterator app.command
      $name: '%app.name%'
      $version: '%app.version%'
    calls:
      - setDispatcher: [ '@app.event_dispatcher' ]