scrape_configs:
  - job_name: is_cron_running
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8181']
  - job_name: process-exporter
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9256' ]
#  - job_name: node_exporter
#    scrape_interval: 5s
#    static_configs:
#      - targets: [ 'host.docker.internal:9100' ]